name = "PhysicalOceanography"
uuid = "e1a20e90-c40e-46c0-93e3-c2da05da97e3"
authors = ["Gael Forget <gforget@mit.edu>"]
version = "0.1.2"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
